#!/bin/bash

################################################################################
# bash_arrays - Basic array functions
#
#   Copyright (c) 2009-10 Dave Olszewski <cxreg@pobox.com>
#   http://github.com/cxreg/cxregs-bash-tools
#
#   This code is released under GPL v2 and the Artistic License, and
#   may be redistributed under the terms of either.
#
#
#   While bash gives you support for using variables as arrays, which is a
#   great improvement over using a space-delimited list, it still leaves it
#   difficult to make use of this feature.  This library aimes to improve
#   the situation.
#
#   The provided functions are as follows:
#
#       apush
#         Description: Add an element to the end of your array
#         Usage:       $ apush var_name elem1 [elem2...]
#
#       apop
#         Description: Remove the last element from the array and print it
#         Usage:       $ apop var_name
#
#       ashift
#         Description: Remove the first element from the array and print it
#         Usage:       $ ashift var_name
#
#       aunshift
#         Description: Add an element to the beginning of the array
#         Usage:       $ aunshift var_name elem1 [elem2...]
#
#       areverse
#         Description: Reverse the order of elements in the array
#         Usage:       $ areverse var_name
#
#       afirst
#         Description: Like ashift, but doesn't remove anything.
#         Usage:       $ afirst var_name
#
#       alast
#         Description: Like apop, but doesn't remove anything.
#         Usage:       $ alast var_name
#
#       alen
#         Description: Print the current number of elements in the array
#         Usage:       $ alen var_name
#
#   If the incorrect number of arguments are supplied, all functions exit
#   silently.  This is subject to change in the future.
#
#   This library was inspired largely by having access to this functionality
#   in Perl, and then finding it severely lacking in bash.
################################################################################

# Set some variables for zsh vs bash
if [[ -n $ZSH_VERSION ]]; then
    array_len_to_last_elem=0
    array_first_index=1
    array_offset="+1"
else
    array_len_to_last_elem=1
    array_first_index=0
    array_offset="-1"
fi

function apush() {
    local var=$1; shift

    if [[ -n $var ]]; then
        eval "$var+=(\"\$@\")"
    fi
}

function apop() {
    local var=$1

    local _apop_return=

    if [[ -n $var ]] && (( $(eval "echo \${#$var""[@]}") >= 1 )); then
        if [[ -n $ZSH_VERSION ]]; then
            eval "_apop_return=\"\$$var""[-1]\""
            eval "$var""[-1]=()"
        else
            eval "_apop_return=\$(echo \${$var[\${#$var""[@]} - $array_len_to_last_elem]})"
            eval "unset $var""[\$(( \${#$var""[@]} - $array_len_to_last_elem))]"
        fi
    fi

    echo $_apop_return
}

function ashift() {
    local var=$1

    local _ashift_return=

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "_ashift_return=\${$var""[$array_first_index]}"
        if [[ -n $ZSH_VERSION ]]; then
            eval "$var""[$array_first_index]=()"
        else
            eval "unset $var[0]"
            eval "$var=(\"\${$var[@]}\")"
        fi
    fi

    echo $_ashift_return
}

# Bash requires the array be quoted, zsh requires it not
function aunshift() {
    local var=$1; shift

    if [[ -n $ZSH_VERSION ]]; then
        eval "$var=(\"\$@\" \${$var[@]})"
    else
        eval "$var=(\"\$@\" \"\${$var[@]}\")"
    fi
}

function areverse() {
    local var=$1

    if [[ -n $var ]] && (( $(eval "echo \${#$var""[@]}") >= 2 )); then
        len=$(eval "echo \${#$var""[@]}")
        i=$array_first_index
        if [[ -n $ZSH_VERSION ]]; then
            local op='<='
        else
            local op='<'
        fi
        while (( $i $op $len/2 )); do
            tmp=$(eval echo "\${$var""[\$i]}")

            eval "$var""[\$i]=\"\${$var""[\$len-\$i$array_offset]}\""
            eval "$var""[\$len-\$i$array_offset]=\"\$tmp\""
            (( i++ ))
        done
    fi
}

function afirst() {
    local var=$1

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "echo \${$var""[$array_first_index]}"
    fi
}

function alast() {
    local var=$1

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "echo \${$var""[\${#$var[@]} - $array_len_to_last_elem]}"
    fi
}

function alen() {
    local var=$1

    eval "echo \${#$var[@]}"
}
