#!/bin/bash

################################################################################
# bash_arrays - Basic array functions
#
#   Copyright (c) 2009,2012 Dave Olszewski <cxreg@pobox.com>
#   http://github.com/cxreg/smartcd
#
#   This code is released under GPL v2 and the Artistic License, and
#   may be redistributed under the terms of either.
#
#
#   While bash gives you support for using variables as arrays, which is a
#   great improvement over using a space-delimited list, it still leaves it
#   difficult to make use of this feature.  This library aims to improve
#   the situation.
#
#   The provided functions are as follows:
#
#       apush
#         Description: Add an element to the end of your array
#         Usage:       $ apush var_name elem1 [elem2...]
#
#       apop
#         Description: Remove the last element from the array and print it.
#                      The value is also set to the variable _apop_return.
#         Usage:       $ apop var_name
#
#       ashift
#         Description: Remove the first element from the array and print it
#                      The value is also set to the variable _ashift_return.
#         Usage:       $ ashift var_name
#
#       aunshift
#         Description: Add an element to the beginning of the array
#         Usage:       $ aunshift var_name elem1 [elem2...]
#
#       areverse
#         Description: Reverse the order of elements in the array
#         Usage:       $ areverse var_name
#
#       afirst
#         Description: Like ashift, but doesn't remove anything.
#         Usage:       $ afirst var_name
#
#       alast
#         Description: Like apop, but doesn't remove anything.
#         Usage:       $ alast var_name
#
#       anth
#         Description: Retreive the n-th element of an array.
#         Usage:       $ anth var_name n
#
#       alen
#         Description: Print the current number of elements in the array
#         Usage:       $ alen var_name
#
#       acopy
#         Description: Copy the contents of an array into a new variable.
#         Usage:       $ alen var_name new_variable
#
#   If the incorrect number of arguments are supplied, all functions exit
#   silently.  This is subject to change in the future.
#
#   This library was inspired largely by having access to this functionality
#   in Perl, and then finding it severely lacking in bash.
################################################################################

# Set some variables for zsh vs bash
function determine_array_type() {
    if [[ -n $ZSH_VERSION ]]; then
        local zsharrays=1
        for opt in $(setopt); do
            case $opt in
                ksharrays) zsharrays=;;
            esac
        done
    fi
    if [[ -n $zsharrays ]]; then
        array_len_to_last_elem=0
        array_first_index=1
        array_offset="+1"
    else
        array_len_to_last_elem=1
        array_first_index=0
        array_offset="-1"
    fi
}

function is_array() {
    local var=$1

    if [[ -n $ZSH_VERSION ]]; then
        local pattern="^typeset"
    else
        local pattern="^declare"
    fi

    type=$(declare -p $var 2>/dev/null)
    if [[ $type =~ $pattern" -a" ]]; then
        echo 1
    fi
}

# It's not really possible to "echo" an array copy and catch it correctly
# so instead we'll ask for the destination
function acopy() {
    local var=$1; shift
    local dest=$1; shift

    if [[ -n $(is_array $var) && -n $dest ]]; then
        eval "$dest=(\"\${$var""[@]}\")"
    fi
}

function apush() {
    local var=$1; shift

    if [[ -n $var ]]; then
        if [[ -n $ZSH_VERSION ]]; then
            eval "$var=(\${$var[@]} \"\$@\")"
        else
            eval "$var=(\"\${$var[@]}\" \"\$@\")"
        fi
    fi
}

function apop() {
    local var=$1
    determine_array_type

    _apop_return=

    if [[ -n $var ]] && (( $(eval "echo \${#$var""[@]}") >= 1 )); then
        if [[ -n $ZSH_VERSION ]]; then
            eval "_apop_return=\"\$$var""[-1]\""
            eval "$var""[-1]=()"
        else
            eval "_apop_return=\"\$(echo \"\${$var[\${#$var""[@]} - $array_len_to_last_elem]}\")\""
            eval "unset $var""[\$(( \${#$var""[@]} - $array_len_to_last_elem))]"
        fi

        echo "$_apop_return"
    fi
}

function ashift() {
    local var=$1
    determine_array_type

    _ashift_return=

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "_ashift_return=\"\${$var""[$array_first_index]}\""
        if [[ -n $ZSH_VERSION ]]; then
            eval "$var""[$array_first_index]=()"
        else
            eval "unset $var[0]"
            eval "$var=(\"\${$var[@]}\")"
        fi

        echo "$_ashift_return"
    fi
}

# Bash requires the array be quoted, zsh requires it not
function aunshift() {
    local var=$1; shift

    if [[ -n $var ]]; then
        if [[ -n $ZSH_VERSION ]]; then
            eval "$var=(\"\$@\" \${$var[@]})"
        else
            eval "$var=(\"\$@\" \"\${$var[@]}\")"
        fi
    fi
}

function areverse() {
    local var=$1
    determine_array_type

    if [[ -n $var ]] && (( $(eval "echo \${#$var""[@]}") >= 2 )); then
        len=$(eval "echo \${#$var""[@]}")
        i=$array_first_index
        if [[ -n $ZSH_VERSION ]]; then
            local op='<='
        else
            local op='<'
        fi
        while (( $i $op $len/2 )); do
            tmp=$(eval echo "\${$var""[\$i]}")

            eval "$var""[\$i]=\"\${$var""[\$len-\$i$array_offset]}\""
            eval "$var""[\$len-\$i$array_offset]=\"\$tmp\""
            (( i++ ))
        done
    fi
}

function afirst() {
    local var=$1
    determine_array_type

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "echo \"\${$var""[$array_first_index]}\""
    fi
}

function alast() {
    local var=$1
    determine_array_type

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "echo \"\${$var""[\${#$var[@]} - $array_len_to_last_elem]}\""
    fi
}

function anth() {
    local var=$1
    local n=$2
    determine_array_type

    if [[ -n $var ]] && (( $(eval "echo \${#$var[@]}") >= 1 )); then
        eval "echo \"\${$var""[$(($array_first_index + $n - 1))]}\""
    fi
}

function alen() {
    local var=$1

    if [[ -n $var ]]; then
        eval "echo \${#$var[@]}"
    fi
}

# Run deferred smartcd if we're waiting for it, and varstash is also loaded
if [[ -n "$smartcd_initially_deferred" && -n "$(fn_exists autostash)" ]]; then
    smartcd_skip_action=1
    smartcd_run_mainline=1
    smartcd cd
    unset smartcd_skip_action
    unset smartcd_initially_deferred
fi
