#!/bin/bash
#
# If you would like to install smartcd, run the following command and
# it will download and install itself.
#
#   % curl -L http://cxreg.com/smartcd | bash
#
# If you don't have curl, but you do have wget, replace `curl -L` with `wget -O -`.
#
# For more details about this program, visit http://github.com/cxreg/smartcd

baseurl="https://raw.github.com/cxreg/smartcd/master"
curl=$(which curl)
wget=$(which wget)
if [[ -n $curl ]]; then
    download="curl -L"
elif [[ -n $wget ]]; then
    download="wget -O -"
else
    echo "I can't find either wget or curl on your system, sorry!  Please download"
    echo "smartcd from http://github.com/cxreg/smartcd and follow the install"
    echo "instructions included."
fi

working_dir=$(mktemp -d)
cd $working_dir
$download "$baseurl/bash_smartcd" > ~/.bash_smartcd
$download "$baseurl/bash_varstash" > ~/.bash_varstash
$download "$baseurl/bash_arrayas" > ~/.bash_arrays
$download "$baseurl/setup.sh" > setup.sh
bash ./setup.sh

cd ~
rm -rf $working_dir

echo "Congratulations, you have installed smartcd!"
