#!/bin/bash

################################################################################
# smartcd - cd with some oomph
#
#   Copyright (c) 2009,2012 Dave Olszewski <cxreg@pobox.com>
#   http://github.com/cxreg/smartcd
#
#   This code is released under GPL v2 and the Artistic License, and
#   may be redistributed under the terms of either.
#
#
#   ###########
#   # Summary #
#   ###########
#
#   This replacement for bash's built-in cd function gives you the
#   ability to run bash_enter and bash_leave scripts for each of
#   the directories you are traveling between.  The scripts are run
#   in the expected order to the most common root between where you
#   are, and where you're going.  These files reside in a hierarchy
#   under your home directory which mirrors the directories they
#   represent, for example:
#
#       /foo/bar/baz  ->  ~/.smartcd/scripts/foo/bar/baz
#
#   ###############
#   # Basic usage #
#   ###############
#
#       # Install the library
#       make install
#
#       # Add it to your bash init script
#       smartcd setup cd # replaces cd with cd()
#
#       # And it works with pushd/popd too
#       smartcd setup pushd
#       smartcd setup popd
#
#       If you are an "autocd" user, you may want
#       smartcd setup prompt-hook
#
#       # Edit the file to create some commands to run when entering
#       smartcd edit enter
#
#       # Non-interactively
#       echo 'echo "hi!"' | smartcd edit enter
#
#       # Or done manually
#       echo 'echo "hi!"' > ~/.smartcd/scripts/somedir/bash_enter
#
#       # When a shell is started enter scripts will be run from / up to your
#       # current directory.  If you want the inverse to occur as well, having
#       # leave scripts run on shell exit, you'll want to hook the shell's EXIT
#       # trap like this:
#       smartcd setup exit-hook
#
#   This library combines very nicely with varstash to allow
#   you to set per-directory environment variables:
#
#       # bash_enter
#       stash PATH
#       export PATH=/something/extra:$PATH
#
#       # bash_leave
#       unstash PATH
#
#       # or the automagic version, which unstashes for you
#       autostash PATH
#       export PATH=/something/extra:$PATH
#
#   When a script is run by smartcd, it will announce that it has done
#   so unless SMARTCD_QUIET is set.
#
#   ########################
#   # Legacy mode (unsafe) #
#   ########################
#
#   The original version of this library was such that the scripts
#   containing the commands to run were themselves located in the
#   directory which they correspond to, named .bash_enter and
#   .bash_leave:
#
#       /foo/bar/baz  ->  /foo/bar/baz/.bash_enter
#
#   This was deemed unsafe, and the new scheme was adopted.  If you
#   prefer the old system and wish to accept the risk in doing so, you
#   can set SMARTCD_LEGACY=1 to allow the old behavior.  If you do not do
#   so, and a legacy script is found, it will *NOT* be invoked, and
#   instructions for migrating it to the new location will be displayed
#   (unless SMARTCD_QUIET is set).  If you set SMARTCD_AUTOMIGRATE=1 then
#   the migration steps will be executed for you whenever a legacy script
#   is found.
#
#   #############
#   # Templates #
#   #############
#
#   One advanced feature of smartcd is the ability to configure and use
#   templates for your enter and leave scripts.  If you often find yourself
#   creating very similar scripts with only minor differences, templates can
#   help.  This is handled with "smartcd template".
#
#   To create a template based on the current directory, run:
#
#       smartcd template create template_name
#
#   The name can be any arbitrary value, but should be meaningful to you and
#   should not contain special characters.  This will create a new template
#   named what you have chosen, and prepopulate it with the contents from
#   your current bash_enter and bash_leave scripts.  You can then edit the
#   file and save it.  When you install the template, anywhere you inserted
#   the string "__PATH__" will be replaced with the directory being set up.
#
#   To install the template, cd to a destination and run:
#
#       smartcd template install template_name
#
#   The other available commands are:
#
#       smartcd template list
#       smartcd template show <name>
#       smartcd template edit <name>
#       smartcd template delete <name>
#
#   ##############
#   # Backing up #
#   ##############
#
#   You may find it valuable to back up your scripts and templates, either
#   for preventative measures, or to copy your scripts to another machine.
#   In any case, a import and export feature is provided to allow you to
#   archive these files and restore them to a ~/.smartcd folder.
#
#       # Export your scripts
#       smartcd export > my_smartcd_backup
#
#       # Several methods to import them
#       smartcd import my_smartcd_backup
#       cat my_smartcd_backup | smartcd import
#
#   If it happens that the machine you are importing to already has a ~/.smartcd
#   directory with any scripts or templates in it, these files will be moved
#   to a temp folder to avoid any conflict.  You may want to inspect these files
#   by hand if this occurs and put them back in place if necessary.
#
################################################################################

# Compatibility functions
function smartpushd() { smartcd pushd "$@"; }
function smartpopd()  { smartcd popd "$@";  }

function smartcd() {
    if [[ ! -t 1 ]] && (( ${SMARTCD_QUIET:-1} > 0 )); then
        SMARTCD_QUIET=1
        local suppress_output=1
    fi

    local command="$1"

    if [[ $# == "2" && $* == "cd ." ]]; then
        command="reenter"
    fi

    local usage="Usage: smartcd ( edit | show | filename | template | setup | config | export | import ) [args]"
    case $command in
        -h|help|'') echo $usage;;
     cd|pushd|popd) shift; _smartcd $command "$@"; return $?;;
           reenter) local dir="$(pwd)"
                    _smartcd cd ..
                    _smartcd cd "$dir"
                    ;;
     edit|show|cat|\
          filename) shift; local file=$1; shift
                    case $file in
                                   enter|leave) _smartcd_file_check bash_$file $command  "$@";;
                         bash_enter|bash_leave) _smartcd_file_check $file $command  "$@";;
                                             *) echo "Usage: smartcd $command ( enter | leave )";;
                    esac
                    ;;
          template) shift; smartcd_template "$@";;
             setup) shift; local setup=$1; shift;
                    case $setup in
                             cd|pushd|popd) setup_smartcd_function $setup;;
                        prompt-hook|prompt) setup_smartcd_prompt_hook;;
                          chpwd-hook|chpwd) setup_smartcd_chpwd_hook;;
                            exit-hook|exit) setup_smartcd_exit_hook;;
                                completion) _smartcd_load "completion";;
                    esac
                    ;;
            config) smartcd_config;;
            export) shift; smartcd_export "$@";;
            import) shift; smartcd_import "$@";;
            inform) shift; if [[ -z $suppress_output ]]; then echo "$@"; fi;;
                 *) if [[ -n $ZSH_VERSION ]]; then
                        local dir=$argv[-1]
                    else
                        local dir=${!#}
                    fi
                    if [[ -d $dir ]]; then
                        if [[ -z $smartcd_warned_alias ]]; then
                            echo "You appear to have smartcd set up in a deprecated fashion.  Please update your"
                            echo "configuration.  If it currently looks like this:"
                            echo
                            echo "   alias cd=smartcd"
                            echo "   alias pushd=smartpushd"
                            echo "   alias popd=smartpopd"
                            echo
                            echo "you should update it to instead say this:"
                            echo
                            echo "   smartcd setup cd"
                            echo "   smartcd setup pushd"
                            echo "   smartcd setup popd"
                            echo
                            echo "If you are getting this message incorrectly or don't know what it means, run"
                            echo "\`smartcd config\`, or email cxreg@pobox.com for help."
                            smartcd_warned_alias=1
                        fi
                        _smartcd cd "$@"
                    else
                        echo $usage
                    fi
                    ;;
    esac
}

# Load bits of functionality from files
function _smartcd_load() {
    local file="$1"
    local smartcd_file="$(_smartcd_file)"
    eval "source ${smartcd_file/%smartcd/$file}"
}

function _smartcd_exec_file() {
    local contents="$(cat "$1")"
    _smartcd_exec "$contents" "$2"
}

function _smartcd_exec() {
    local contents="${1//__PATH__/$2}"
    eval "$contents"
}

function _smartcd_check_inode() {
    if [[ -n $SMARTCD_NO_INODE ]]; then
        return
    fi
    local dir=$1;
    if [[ ! -d "$dir" ]]; then
        # Don't barf when leaving deleted directory
        return
    fi
    local inode=$(command ls -di "$dir" | command awk '{print $1}')
    if [[ -f "$HOME/.smartcd/inodes$dir.inode" ]]; then
        prev=$(command cat "$HOME/.smartcd/inodes$dir.inode")
        if [[ $prev != "*" && $inode != $prev ]]; then
            echo "WARNING!  Possibly outdated scripts detected, not running them.  These"
            echo "scripts were created for a directory which has been deleted or replaced,"
            echo "but the scripts for them remained.  Please check the following files"
            echo "for correctness:"
            echo
            local _old_ifs="$IFS"
            IFS=$'\n'
            for file in $(command ls "$HOME/.smartcd/scripts$dir"); do
                echo "    $HOME/.smartcd/scripts$dir/$file"
            IFS="$_old_ifs"
            done
            echo
            echo "Once you have verified or corrected the situation, remove the following"
            echo "file to make this warning go away"
            echo
            echo "    $HOME/.smartcd/inodes$dir.inode"
            echo
            echo "If you don't wish to keep this safety check in place, set SMARTCD_NO_INODE=1"
            echo "or re-run \`smartcd config\`"
            echo
            echo "To permanently ignore this check only for $dir, run the following command"
            echo
            echo "    echo '*' > \"$HOME/.smartcd/inodes$dir.inode\""
            _inode_skip=1
        fi
    else
        command mkdir -p "$HOME/.smartcd/inodes$dir"
        echo $inode > "$HOME/.smartcd/inodes$dir.inode"
    fi
}

function _smartcd() {
    # Don't run this twice consecutively from being sourced.  If the user double-sources
    # then it could result in scripts being run twice which may have undesirable or
    # unpredictable effects, so don't do that
    if [[ -n $smartcd_run_mainline ]]; then
        if [[ -n $smartcd_last_run_mainline ]]; then
            unset smartcd_run_mainline
            return
        else
            smartcd_last_run_mainline=1
        fi
    else
        unset smartcd_last_run_mainline
    fi
    unset smartcd_run_mainline

    # What are we being invoked as?
    local action="builtin $1"; shift

    # First, take note of where we're starting from
    local wherenow="${_smartcd_last_run_for#x}"
    local wherestarted="$wherenow"
    if [[ -z "$wherestarted" ]]; then
        wherestarted=/
        local initial_mode=1
    fi
    local run_from_smartcd=1
    local _ashift_return
    local _apop_return

    if [[ -z "$(fn_exists apush)" ]]; then
        echo "array library is not loaded, please ensure that it is installed before using smartcd"
        return
    fi

    # If this is zsh and the user has chpwd enabled, it will fire a whole lot of times
    # during this.  Stash it and disable it until we're done.
    if [[ -n $ZSH_VERSION && -n "$(fn_exists stash)" ]]; then
        local varstash_dir="$wherestarted"
        stash -f chpwd
        stash -f chpwd_functions
        unset -f chpwd 2>/dev/null
        unset chpwd_functions 2>/dev/null
        unset -v varstash_dir
        local stashed_chpwd=1
    fi

    # Go there and get the fully qualified path.  Also, fail first if it's an
    # invalid destination, before we do any more work.
    local _old_ifs="$IFS"
    IFS=$' \t\n'
    if [[ -z $smartcd_skip_action ]]; then
        if [[ -n $1 ]] || [[ -z ${1-_} ]]; then
            if [[ -n $ZSH_VERSION ]]; then
                ${=action} "$@"
            else
                $action "$@"
            fi
        else
            eval $action
        fi
    fi
    local rv=$?
    IFS="$_old_ifs"

    if (( $rv != 0 )); then return $rv; fi
    local whereto="$(pwd)"
    _smartcd_last_run_for="x$whereto"

    # If zsh, turn autopushd off temporarily to avoid extra pushes
    if [[ -n $ZSH_VERSION ]]; then
        setopt localoptions
        setopt noautopushd
        setopt nopushdignoredups
    fi

    # Collect the list of directories we're leaving
    unset leave_stack
    while [[ -n $wherenow ]]; do
        apush leave_stack "$wherenow"
        wherenow="${wherenow%/*}"
    done
    if [[ -z $initial_mode ]]; then
        apush leave_stack "/"
    fi

    # Collect the list of directories we're entering, but enter nothing if
    # we're in "exit mode" which just runs all leave scripts
    if [[ -z $smartcd_exiting ]]; then
        wherenow="$whereto"
        unset enter_stack
        while [[ -n $wherenow ]]; do
            apush enter_stack "$wherenow"
            wherenow=${wherenow%/*}
        done
        apush enter_stack "/"
    fi

    # Pop off common elements
    while [[ -n "$(alast enter_stack)" ]] && [[ "$(alast enter_stack)" == "$(alast leave_stack)" ]]; do

        # Special cases for /, otherwise it would never be possible to run enter/leave for it
        if [[ "$(alen enter_stack)" == "1" ]] && [[ "$(afirst enter_stack)" == "/" ]]; then
            apop leave_stack >/dev/null
            break
        elif [[ "$(alen leave_stack)" == "1" ]] && [[ "$(afirst leave_stack)" == "/" ]]; then
            apop enter_stack >/dev/null
            break
        fi

        apop enter_stack >/dev/null
        apop leave_stack >/dev/null
    done

    # Run leave_stack in lowest to highest
    local stack_size=$(alen leave_stack)
    : ${stack_size:=0}
    local smartcd_runmode=leave
    while (( $stack_size >= 1 )); do
        # ashift in a sub-shell doesn't work
        local dir="$(afirst leave_stack)"
        ashift leave_stack >/dev/null

        # Set this just in case we are not able to actualy chdir to $dir
        local varstash_dir="$dir"

        local confdir="$HOME/.smartcd/scripts$dir"
        local olddir="$HOME/.smartcd$dir"
        if [[ -d "$dir" ]]; then
            builtin cd "$dir"
            if [[ -f .bash_leave ]]; then
                if [[ -n $SMARTCD_LEGACY ]]; then
                    if (( ${SMARTCD_QUIET:-0} == 0 )); then
                        echo "smartcd: running $dir/.bash_leave"
                    fi
                    _smartcd_exec_file .bash_leave "$dir"
                elif [[ -n $SMARTCD_AUTOMIGRATE ]]; then
                    echo "Automatically migrating \"$dir/.bash_leave\" to \"$confdir/bash_leave\""
                    command mkdir -p "$confdir"
                    command cat "$dir/.bash_leave" >> "$confdir/bash_leave"
                    command rm "$dir/.bash_leave"
                elif (( ${SMARTCD_QUIET:-0} == 0 )); then
                    echo "############################################################################"
                    echo "# NOTICE!  Deprecated .bash_leave found, please migrate this file to the new"
                    echo "# format using the following (or similar) commands:"
                    if [[ ! -d $confdir ]]; then
                        echo "mkdir -p \"$confdir\""
                    fi
                    echo "cat \"$dir/.bash_leave\" >> \"$confdir/bash_leave\""
                    echo "rm \"$dir/.bash_leave\""
                    echo "#"
                    echo "# If you would like smartcd to perform this migration for you whenever"
                    echo "# possible, set SMARTCD_AUTOMIGRATE=1"
                    echo "#"
                    echo "# If you wish to accept the risks of the old style of operation and run"
                    echo "# them as-is, you may set SMARTCD_LEGACY=1 instead."
                    echo "############################################################################"
                fi
            fi
        else
            echo "smartcd: leaving non-existent directory $dir"
        fi

        if [[ -f "$olddir/bash_leave" ]]; then
            smartcd_upgrade_database
        fi

        # We will run this even if we were not able to chdir there, but
        # the user is notified that this occurred so they can check things out
        if [[ -f "$confdir/bash_leave" ]]; then
            if (( ${SMARTCD_QUIET:-0} == 0 )); then
                echo "smartcd: running $confdir/bash_leave"
            fi
            _smartcd_check_inode "$dir"
            if [[ -z $_inode_skip ]]; then
                _smartcd_exec_file "$confdir/bash_leave" "$dir"
            fi
            unset -v _inode_skip
        fi

        if [[ -n "$(fn_exists autounstash)" ]]; then
            autounstash
        fi

        stack_size=$(alen leave_stack)
        : ${stack_size:=0}
    done
    unset -v varstash_dir

    # Run enter_stack in highest to lowest
    local stack_size=$(alen enter_stack)
    : ${stack_size:=0}
    local smartcd_runmode=enter
    while (( $stack_size >= 1 )); do
        # apop in a sub-shell doesn't work
        local dir="$(alast enter_stack)"
        apop enter_stack >/dev/null
        builtin cd "$dir"
        local confdir="$HOME/.smartcd/scripts$dir"
        local olddir="$HOME/.smartcd$dir"
        if [[ -f .bash_enter ]]; then
            if [[ -n $SMARTCD_LEGACY ]]; then
                if (( ${SMARTCD_QUIET:-0} == 0 )); then
                    echo "smartcd: running $dir/.bash_enter"
                fi
                _smartcd_exec_file .bash_enter "$dir"
            elif [[ -n $SMARTCD_AUTOMIGRATE ]]; then
                echo "Automatically migrating \"$dir/.bash_enter\" to \"$confdir/bash_enter\""
                command mkdir -p "$confdir"
                command cat "$dir/.bash_enter" >> "$confdir/bash_enter"
                command rm "$dir/.bash_enter"
            elif (( ${SMARTCD_QUIET:-0} == 0 )); then
                echo "############################################################################"
                echo "# NOTICE!  Deprecated .bash_enter found, please migrate this file to the new"
                echo "# format using the following (or similar) commands:"
                if [[ ! -d $confdir ]]; then
                    echo "mkdir -p \"$confdir\""
                fi
                echo "cat \"$dir/.bash_enter\" >> \"$confdir/bash_enter\""
                echo "rm \"$dir/.bash_enter\""
                echo "#"
                echo "# If you would like smartcd to perform this migration for you whenever"
                echo "# possible, set SMARTCD_AUTOMIGRATE=1"
                echo "#"
                echo "# If you wish to accept the risks of the old style of operation and run"
                echo "# them as-is, you may set SMARTCD_LEGACY=1 instead."
                echo "############################################################################"
            fi
        fi

        if [[ -f "$olddir/bash_enter" ]]; then
            smartcd_upgrade_database
        fi

        if [[ -f "$confdir/bash_enter" ]]; then
            if (( ${SMARTCD_QUIET:-0} == 0 )); then
                echo "smartcd: running $confdir/bash_enter"
            fi
            _smartcd_check_inode "$dir"
            if [[ -z $_inode_skip ]]; then
                _smartcd_exec_file "$confdir/bash_enter" "$dir"
            fi
            unset -v _inode_skip
        fi

        stack_size=$(alen enter_stack)
        : ${stack_size:=0}
    done

    # First go to starting directory, as long as it still exists...
    if [[ -d "$wherestarted" ]]; then
        builtin cd "$wherestarted"
    fi

    # ...restoring any chpwd hooks in the process, and allow them to fire once (now)...
    if [[ -n $stashed_chpwd ]]; then
        # However, if smartcd was called from a hook and we're still here, then that
        # means that the chdir happened _before_ we started and thus the hook already
        # fired.  So go there before re-adding the hooks.
        if [[ -n $smartcd_skip_action ]]; then
            builtin cd "$whereto"
            local arrived_at_destination=1
        fi
        unstash chpwd
        unstash chpwd_functions
    fi

    # ... and then jump to final directory to stay
    if [[ -z $arrived_at_destination ]]; then
        builtin cd "$whereto"
    fi
}

function smartcd_edit() {
    # Invoke the users editor (or vi) on the relevant file
    local file="$1"
    case $file in
        bash_enter|bash_leave) local type=${file#bash_};;
                  enter|leave) local type=$file; file="bash_$file";;
                            *) echo "Usage: smartcd_edit ( bash_enter | bash_leave )"
                               return
                               ;;
    esac

    if [[ -f "$HOME/.smartcd$(pwd)/$file" ]]; then
        smartcd_upgrade_database
    fi

    local smartcd_dir="$HOME/.smartcd/scripts$(pwd)"
    if [[ ! -d "$smartcd_dir" ]]; then
        command mkdir -p "$smartcd_dir"
    fi

    # Edit the file if interactive, otherwise write standard input to it
    if [[ -t 0 ]]; then
        local tmpfile=$(mktemp /tmp/smartcd-edit.XXXXXX) line=
        local _old_ifs="$IFS"
        IFS=$'\n'
        if [[ -f "$smartcd_dir/$file" ]]; then
            while builtin read -r line; do
                case $line in
                    # extremely hinky replacement here, very whitespace sensitive
                    *"smartcd template run"*) local tmpl=${line##*template run }
                                            tmpl=${tmpl%% *}
                                            echo "$line" >> "$tmpfile"
                                            echo "$(smartcd template show_part $tmpl ${file#bash_})" >> "$tmpfile"
                                            ;;
                                        *) echo "$line" >> "$tmpfile";;
                esac
            done < "$smartcd_dir/$file"
        else
            if [[ $type == "enter" ]]; then
                local enter_usage=$(cat <<EOF
  Some examples are editing your \$PATH or creating
# a temporary alias:
#
#     autostash PATH=__PATH__/bin:\$PATH
#     autostash alias restart="service stop; sleep 1; service start"
EOF
)
            fi
            command cat > "$tmpfile" << EOF
########################################################################
# smartcd $type - $(pwd)
#
# This is a smartcd script.  Commands you type will be run when you
# $type this directory.  The string __PATH__ will be replaced with
# the current path.$enter_usage
#
# See http://smartcd.org for more ideas about what can be put here
########################################################################
EOF
        fi
        ${EDITOR:-vi} "$tmpfile"
        if [[ $? == 0 ]]; then
            echo -n > "$smartcd_dir/$file"
            if [[ -s "$tmpfile" ]]; then
                local writing=1
                while builtin read -r line; do
                    case $line in
                        "# begin smartcd template"*) writing=;;
                        "# end smartcd template"*) writing=1;;
                                                *) if [[ -n $writing ]]; then echo "$line" >> "$smartcd_dir/$file"; fi;;
                    esac
                done < "$tmpfile"
            fi
        fi
        IFS="$_old_ifs"
        rm "$tmpfile"
    else
        command cat > "$smartcd_dir/$file"
    fi

    if [[ -f "$smartcd_dir/$file" && ! -s "$smartcd_dir/$file" ]]; then
        # Delete any file that is left empty
        command rm "$smartcd_dir/$file"
    fi
}

function _smartcd_hook() {
    local cwd="$(pwd)"

    # Skip this if we already ran smartcd for this directory
    if [[ "x$cwd" != "$_smartcd_last_run_for" ]]; then
        local smartcd_skip_action=1
        smartcd cd "$cwd"
    fi

    eval $_smartcd_original_command
}

function setup_smartcd_function() {
    local cmd=$1;
    if typeset -f rvm >/dev/null 2>/dev/null &&
      typeset -f __rvm_setup_cd_function >/dev/null 2>/dev/null
    then
        __rvm_setup_cd_function smartcd $cmd
    else
        eval "function $cmd() { smartcd $cmd \"\$@\"; }"
    fi
}

function setup_smartcd_prompt_hook() {
    if [[ -n $ZSH_VERSION ]]; then
        if [[ -z "$(fn_exists apush)" ]]; then
            echo "array library is not loaded, please ensure that it is installed before using smartcd"
            return
        fi
        _smartcd_original_command=:
        apush precmd_functions _smartcd_hook
    else
        if [[ -n $PROMPT_COMMAND && -z $_smartcd_original_command ]]; then
            _smartcd_original_command=$PROMPT_COMMAND
        else
            _smartcd_original_command=:
        fi

        PROMPT_COMMAND=_smartcd_hook
    fi
}

function setup_smartcd_chpwd_hook() {
    if [[ -n $ZSH_VERSION ]]; then
        if [[ -z "$(fn_exists apush)" ]]; then
            echo "array library is not loaded, please ensure that it is installed before using smartcd"
            return
        fi
        _smartcd_original_command=:
        apush chpwd_functions _smartcd_hook
    fi
}

function setup_smartcd_exit_hook() {
    if [[ -n $_smartcd_exit_trap_setup ]]; then
        return
    fi

    if [[ -n $ZSH_VERSION ]]; then
        apush zshexit_functions _smartcd_exit_trap
    else
        # Bash supports this, which is much cleaner
        _smartcd_original_exit_trap=$(trap -p EXIT)
        _smartcd_original_exit_trap=${_smartcd_original_exit_trap#trap -- }
        _smartcd_original_exit_trap=${_smartcd_original_exit_trap% EXIT}
        trap _smartcd_exit_trap EXIT
    fi

    _smartcd_exit_trap_setup=1
}

function _smartcd_exit_trap() {
    local smartcd_exiting=1
    smartcd cd /

    if [[ -n $_smartcd_original_exit_trap ]]; then
        eval $_smartcd_original_exit_trap
    fi
}

function bash_enter() {
    _smartcd_file_check bash_enter "$@"
}

function bash_leave() {
    _smartcd_file_check bash_leave "$@"
}

function fn_exists() {
    if [[ -n "$(declare -f $1)" ]]; then
        echo 1
    fi
}

function _smartcd_file() {
    if [[ -n $ZSH_VERSION ]]; then
        # We need the third element because within anth or afirst, arrays is the
        # first two due to the function call and the eval
        local this_file="$(anth funcsourcetrace 3)"
        this_file="${this_file%:*}"
    else
        local this_file="$BASH_SOURCE"
    fi
    if [[ "${this_file%/.smartcd/lib/core/smartcd}" == $HOME ]]; then
        this_file=${this_file/#$HOME/\~}
    fi
    echo "$this_file"
}

# Autoload stubs
function _smartcd_file_check() {
    _smartcd_load "smartcd_edit" && _smartcd_file_check "$@"
}

function smartcd_edit() {
    _smartcd_load "smartcd_edit" && smartcd_edit "$@"
}

function smartcd_config() {
    _smartcd_load "smartcd_config" && smartcd_config "$@"
}

function smartcd_template() {
    _smartcd_load "smartcd_template" && smartcd_template "$@"
}

function smartcd_export() {
    _smartcd_load "smartcd_export" && smartcd_export "$@"
}

function smartcd_import() {
    _smartcd_load "smartcd_export" && smartcd_import "$@"
}

function smartcd_upgrade_database() {
    _smartcd_load "smartcd_upgrade_database" && smartcd_upgrade_database "$@"
}

# Run on load if all the necessary libraries are loaded, otherwise let them do it
if [[ -n "$(fn_exists apush)" && -n "$(fn_exists autostash)" && -z "$SMARTCD_NOINITIAL" ]]; then
    smartcd_skip_action=1
    smartcd_run_mainline=1
    smartcd cd
    unset smartcd_skip_action
else
    smartcd_initially_deferred=1
fi
